package org.iesapp.apps.mysqlbrowser.wizard;

import java.awt.event.ActionListener;
import javax.swing.filechooser.FileFilter;


/*
 *
 * @author Josep
 */
public class Step1 extends javax.swing.JPanel {

    /**
     * Creates new form StartupStep3
     */
    public Step1() {
        initComponents();
        FileFilter filter1 = new ExtensionFileFilter("Excel .xls", new String[] { "xls" });
        jFileChooser1.setFileFilter(filter1);
        jFileChooser1.addChoosableFileFilter(filter1);
        jFileChooser1.setMultiSelectionEnabled(false);
    }
    
     public void registerActionListener(ActionListener actionListener) {
        jFileChooser1.addActionListener(actionListener);
     }
   
   
     public java.io.File getSelectedFile()
     {
         return jFileChooser1.getSelectedFile();
     }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Selecciona un fitxer EXCEL .xls");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
            .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

  
}
