/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.iesapp.apps.mysqlbrowser.wizard;

import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.WorkbookSettings;
import jxl.read.biff.BiffException;
import org.iesapp.apps.mysqlbrowser.table.LineNumberTableRowHeader;
import org.iesapp.apps.mysqlbrowser.table.MyComboBoxEditor;
import org.iesapp.database.FieldDescriptor;

/**
 *
 * @author Josep
 */
public class Step2 extends javax.swing.JPanel {
    private DefaultListModel model1, model2;
    private DefaultComboBoxModel comboModel1;
    private HashMap<String, String> taules;
    private Workbook workbook;
    protected Sheet selectedSheet;
    private DefaultTableModel modelTable1;
    private String[] excelCols;
    private DefaultTableModel modelTable2;
    private boolean alreadySet = false;

    /**
     * Creates new form StartupStep3
     */
    public Step2() {
        excelCols = new String[]{};
        initComponents();

        jTable1.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTable1.setGridColor(java.awt.Color.gray);
        jTable1.setShowGrid(true);


        jTable2.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTable2.setGridColor(java.awt.Color.gray);
        jTable2.setShowGrid(true);


        
        comboModel1 = new DefaultComboBoxModel();
        jComboBox1.setModel(comboModel1);     
        
        //Monta la taula
        ArrayList<FieldDescriptor> list = ExcelImportWiz.mysql.getDescriptorForTable(ExcelImportWiz.tableName);
        
        for(FieldDescriptor fd: list)
        {
            String pk = fd.isPrimaryKey()?" [PK]":"";
            pk += fd.isAutoIncrement()?"[AUTO]":"";
            modelTable1.addRow( new Object[]{fd.getName()+pk, ""});            
        }
    }
    
    public void setExcelFileName(java.io.File file) {
        
        if(alreadySet) {
            return;
        }
        
        comboModel1 = new DefaultComboBoxModel();
        
        //Gets metainformation of the excel file
          WorkbookSettings ws = new WorkbookSettings();
          ws.setLocale(new Locale("ca", "ES"));
          ws.setEncoding("ISO-8859-1");
          
        try {
            workbook = Workbook.getWorkbook(file, ws);
            String[] sheetNames = workbook.getSheetNames();
            for(String s: sheetNames)
            {
                comboModel1.addElement(s);
            }
            jComboBox1.setModel(comboModel1);        
            
        } catch (IOException ex) {
            Logger.getLogger(Step2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(Step2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        loadMeta();
        //
        alreadySet =true;
    }
    
    public HashMap<String, Integer> getAssociations()
    {
        HashMap<String, Integer> asoc = new HashMap<String, Integer> ();
        
        for(int i=0; i<jTable1.getRowCount(); i++)
        {
            String taula = (String) jTable1.getValueAt(i, 0);
            boolean isauto = taula.contains("AUTO");
            taula = taula.replace("[PK]", "").replace("[AUTO]", "").trim();
      
            String valor = (String) jTable1.getValueAt(i, 1);
            if(valor.isEmpty() && isauto)
            {
                asoc.put(taula,-1);
            }
            else if(valor.isEmpty() && !isauto)
            {
                asoc.put(taula,-2);
            }
            else
            {
                int pos = -1;
                for(int k=0; k<excelCols.length; k++)
                {
                    if(excelCols[k].equals(valor))
                    {
                        pos = k;
                        break;
                    }
                }
                if(pos>0) {
                    asoc.put(taula, pos-1);
                }
            }
        }
        
        return asoc;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFiles = new javax.swing.JLabel();
        jColumnes = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            }}
            ;

            jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel1.setText("Associació dels camps");

            jLabel3.setText("Triau una pàgina del full de càlcul");

            jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jButton1.setText("?");
            jButton1.setToolTipText("Ajuda");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
            jComboBox1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBox1ActionPerformed(evt);
                }
            });

            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informació"));

            jLabel2.setText("Files:");

            jLabel4.setText("Columnes:");

            jFiles.setText(" ");

            jColumnes.setText(" ");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jColumnes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jFiles)
                    .addComponent(jColumnes))
            );

            modelTable1 = new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Camp de la taula", "Columna Excel"
                }
            ) {

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    boolean q = false;
                    if(columnIndex==0)
                    {
                        q=false;
                    }
                    else
                    {
                        if( ((String)jTable1.getValueAt(rowIndex,0)).contains("AUTO"))
                        q=false;
                        else
                        q = true;
                    }

                    return q;
                }
            };
            jTable1.setModel(modelTable1);
            jTable1.getColumnModel().getColumn(1).setCellEditor(new MyComboBoxEditor(excelCols));
            jTable1.setRowHeight(40);
            jScrollPane1.setViewportView(jTable1);

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                    .addContainerGap())
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addContainerGap())
            );

            jTabbedPane1.addTab("Associacions", jPanel2);

            jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

            modelTable2 = new javax.swing.table.DefaultTableModel(
                new Object [][] {
                },
                new String [] {
                }
            );
            jTable2.setModel(modelTable2);
            jTable2.setRowHeight(40);
            jScrollPane2.setViewportView(jTable2);
            LineNumberTableRowHeader tableLineNumber = new LineNumberTableRowHeader(jScrollPane2, jTable2);
            tableLineNumber.setBackground(Color.lightGray);
            jScrollPane2.setRowHeaderView(tableLineNumber);

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addGap(2, 2, 2))
            );

            jTabbedPane1.addTab("Visualitza el full", jPanel3);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTabbedPane1)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jButton1))
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTabbedPane1))
            );
        }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ExcelImportWiz.showQuickHelpDialog(null, "Abrev: identificador unic per a cada professor\n"+
                "Nombre: el nom del professor\nDepart: Abreviatura del departament\nTorn: escriviu "+
                "0=matí, 1=tarda, 2=ambdós\nidSGD: (podeu deixar-ho en blanc de moment) associa amb la id del programa sgd");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        loadMeta();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void loadMeta()
    {
        if(jComboBox1.getSelectedIndex()<0) {
            return;
        }
        
         //Set the sheet and provides metaInformation
        selectedSheet = workbook.getSheet((String) jComboBox1.getSelectedItem());
        int ncols = selectedSheet.getColumns();
        jFiles.setText(""+selectedSheet.getRows());
        jColumnes.setText(""+ncols);
        
        //Carrega els noms de les columnes dins dels comboBoxs
        excelCols = new String[ncols+1];
        excelCols[0] = "";
        String[] columnNames = new String[ncols];
        for(int i=0; i<ncols; i++)
        {
            Cell cell = selectedSheet.getCell(i, 0);
            columnNames[i] = columnLetter(i);
            excelCols[i+1]= "["+columnLetter(i)+"]: "+ cell.getContents()+", ...";
            if( !((String) jTable1.getValueAt(i,0)).contains("AUTO") ) {
                jTable1.setValueAt(excelCols[i+1], i, 1);
            }
        }
        jTable1.getColumnModel().getColumn(1).setCellEditor(new MyComboBoxEditor(excelCols));
        
        //Carrega el full excel dins la taula2
        //Crea primer un model
        modelTable2 = new javax.swing.table.DefaultTableModel(new Object [][]{ },  columnNames);
        jTable2.setModel(modelTable2);
                
        
        for(int i=0; i<selectedSheet.getRows(); i++)
        {
            Object[] obj = new Object[ncols];
            for(int j=0; j< ncols; j++)            
            {
                Cell cell = selectedSheet.getCell(j, i);
                obj[j] = cell.getContents();
            }
            modelTable2.addRow(obj);            
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jColumnes;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jFiles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    private final String[] LETTERS= new String[]{"A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","Y","Z"};
    
    public Sheet getSelectedSheet() {
        return selectedSheet;
    }

    private String columnLetter(int i)
    {
        int n = LETTERS.length;
        int res = i % n;
        int quo = (int) (i / (1.*n));
        if(quo==0) {
            return LETTERS[i];
        }
        if(quo==1) {
            return "A"+LETTERS[i-n];
        }
        return "";
    }
    
   

   
}
