package org.iesapp.apps.mysqlbrowser;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MySqlBrowser.java
 *
 * Created on 25-feb-2012, 13:06:24
 */

 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import org.iesapp.database.MyConnectionBean;
import org.iesapp.database.MyDatabase;

/**
 *
 * @author Josep
 */
public class MysqlConJPanel extends javax.swing.JPanel {
    
    MyDatabase mydatabase;
    private DefaultTreeModel treemodel1;
    private DefaultMutableTreeNode top;
    
    public MysqlConJPanel() throws SQLException {
        
        initComponents();         
    }
    
    public void setConBean(MyConnectionBean con) throws SQLException
    {
        mydatabase = new MyDatabase(con.getHost(), con.getDb(), con.getUser(), con.getPwd(), con.getParameters());
        mydatabase.connect();
        
        //load databases
        top = new DefaultMutableTreeNode(con.getUser()+"@"+con.getHost());
        treemodel1 = new DefaultTreeModel(top);
        jTree1.setModel(treemodel1);
        
     
        String SQL1 = "SHOW DATABASES";
        Statement st = mydatabase.createStatement();
        ResultSet rs1 = mydatabase.getResultSet(SQL1,st);
        while(rs1!=null && rs1.next())
        {
       
            DefaultMutableTreeNode schema = new DefaultMutableTreeNode(rs1.getString(1));
            top.add(schema);
            
            //Carrega les taules de cada schema
             String SQL2 = "SHOW TABLES IN "+schema;
             Statement st2 = mydatabase.createStatement();
             ResultSet rs2 = mydatabase.getResultSet(SQL2,st2);
             while(rs2!=null && rs2.next())
             {
                DefaultMutableTreeNode table = new DefaultMutableTreeNode(rs2.getString(1));
                schema.add(table);
             }
             if(rs2!=null) {
                 rs2.close();
                 st2.close();
             }    
        }
        if(rs1!=null) 
        {
            rs1.close();
            st.close();
        }    
        
        dBEditorPanel1.reset();
        jTree1.expandRow(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        dBEditorPanel1 = new org.iesapp.apps.mysqlbrowser.DBEditorPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        jSplitPane1.setDividerLocation(180);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jSplitPane2.setDividerLocation(180);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setName("jSplitPane2"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane2.setViewportView(jTextArea1);

        jSplitPane2.setTopComponent(jScrollPane2);

        dBEditorPanel1.setName("dBEditorPanel1");
        jSplitPane2.setRightComponent(dBEditorPanel1);

        jSplitPane1.setRightComponent(jSplitPane2);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Root");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("kk");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("pizza");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ravioli");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("bananas");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("mm");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("sasadsd");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setName("jTree1"); // NOI18N
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        
    }//GEN-LAST:event_jTree1MouseClicked

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        TreePath path = evt.getPath();
      
        int length = path.getPathCount();
        
       
        if(length==3) //I am on a table name
        {
            String connection = (String) ((javax.swing.tree.DefaultMutableTreeNode) (path.getPathComponent(length-3))).getUserObject();
            String dbName = (String) ((javax.swing.tree.DefaultMutableTreeNode) (path.getPathComponent(length-2))).getUserObject();
            String tableName = (String) ((javax.swing.tree.DefaultMutableTreeNode) (path.getPathComponent(length-1))).getUserObject();
            
            //System.out.println(connection+dbName+tableName);
           
            
           dBEditorPanel1.setTable(mydatabase, dbName, tableName);
        }
    }//GEN-LAST:event_jTree1ValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.iesapp.apps.mysqlbrowser.DBEditorPanel dBEditorPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
